/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appkasir;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.SQLException;
/**
 *
 * @author USER
 */
public class Loginn extends javax.swing.JFrame {
    Statement st;
    ResultSet rs;
    Koneksi kon;

    /**
     * Creates new form Loginn
     */
    public Loginn() {
        kon = new Koneksi();
        initComponents();
        level();
        setLocationRelativeTo(this);
    }
    
    public void level(){
    try {
            st = kon.con.createStatement();
            String query = "SELECT * FROM tbl_level";
            rs = st.executeQuery(query);
            while(rs.next()){
                Llevel.addItem(rs.getString("LEVEL"));
            }
            rs.close();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        Llevel = new javax.swing.JComboBox<>();
        log = new javax.swing.JButton();
        canc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        username.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        password.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N

        Llevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LlevelActionPerformed(evt);
            }
        });

        log.setBackground(new java.awt.Color(102, 102, 255));
        log.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        log.setText("LOGIN");
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        canc.setBackground(new java.awt.Color(255, 102, 102));
        canc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        canc.setText("BATAL");
        canc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("USERNAME");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("PASSWORD");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("LEVEL");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        jLabel4.setText("HALAMAN PORTAL LOGIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(password, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(username)))
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(Llevel, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(189, 189, 189)
                            .addComponent(log)
                            .addGap(41, 41, 41)
                            .addComponent(canc))))
                .addGap(0, 135, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Llevel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(log)
                    .addComponent(canc))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cancActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        // TODO add your handling code here:
        try {
           st = kon.con.createStatement();
           String sql = "SELECT * FROM tbl_user WHERE USERNAME='"+username.getText()+"' AND PASSWORD='"+password.getText()+"'" ;
           rs = st.executeQuery(sql);
            if (rs.next()) {
                if (username.getText().equals(rs.getString("USERNAME")) && password.getText().equals(rs.getString("PASSWORD")) && Llevel.getSelectedItem().equals("ADMIN")) {
                    if (rs.getString("ID_LEVEL").equals("1")) {
                        userlogin.setUserLogin(rs.getString("NAMA_USER"));
                AppUser a = new AppUser();
                a.setVisible(true);
                this.dispose();
                JOptionPane.showMessageDialog(null, "Welcome "+rs.getString("NAMA_USER"));
                    }else if(rs.getString("ID_LEVEL").equals("2")){
                        JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses level ini");
                    }else if(rs.getString("ID_LEVEL").equals("3")){
                        JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses level ini");
                    }   
                }
                else if (username.getText().equals(rs.getString("USERNAME")) && password.getText().equals(rs.getString("PASSWORD")) && Llevel.getSelectedItem().equals("GUDANG")) {
                    if (rs.getString("ID_LEVEL").equals("2")) {
                        userlogin.setUserLogin(rs.getString("NAMA_USER"));
                        iduser.setiduser(rs.getString("ID_USER"));
                 Fbarang b = new Fbarang();
                 b.setVisible(true);
                 this.dispose();
                 JOptionPane.showMessageDialog(null, "Welcome "+rs.getString("NAMA_USER"));
                    }else if(rs.getString("ID_LEVEL").equals("1")){
                        JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses level ini");
                    }else if(rs.getString("ID_LEVEL").equals("3")){
                        JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses level ini");
                    }   
                }
                else if (username.getText().equals(rs.getString("USERNAME")) && password.getText().equals(rs.getString("PASSWORD")) && Llevel.getSelectedItem().equals("KASIR")) {
                    if (rs.getString("ID_LEVEL").equals("3")) {
                        userlogin.setUserLogin(rs.getString("NAMA_USER"));
                        iduser.setiduser(rs.getString("ID_USER"));
                        Fkasir c = new Fkasir();
                 c.setVisible(true);
                 this.dispose();
                 JOptionPane.showMessageDialog(null, "Welcome "+rs.getString("NAMA_USER"));
                    }else if(rs.getString("ID_LEVEL").equals("1")){
                        JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses level ini");
                    }else if(rs.getString("ID_LEVEL").equals("2")){
                        JOptionPane.showMessageDialog(null, "Anda tidak berhak mengakses level ini");
                    }   
                }
                
                }else{
                JOptionPane.showMessageDialog(null, "Username atau Password tidak terdaftar");
            }
            rs.close();
            st.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_logActionPerformed

    private void LlevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LlevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LlevelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Llevel;
    private javax.swing.JButton canc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton log;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
